import { useMemo, useState } from 'react'
import { createId } from '../lib/store.js'

const numberValue=value=>Number(String(value??'').replace(/[^0-9.-]/g,''))||0

export default function EnhancedAnalysisCenter({mode='formula',initialTarget,setMode,data,commit,close}){
  const [targetId,setTargetId]=useState(initialTarget||data.nodes[0]?.id||'')
  const [expression,setExpression]=useState('')
  const [scenarioId,setScenarioId]=useState(data.scenarios?.[0]?.id||'baseline')
  const results=useMemo(()=>data.nodes.map(node=>({node,value:numberValue(node.value)})),[data.nodes])
  const saveFormula=()=>{if(!targetId||!expression.trim())return;commit(next=>{const existing=next.formulas.find(item=>(item.targetNodeId||item.nodeId)===targetId);const record={id:existing?.id||createId('formula'),name:existing?.name||'Formula',nodeId:targetId,targetNodeId:targetId,expression:expression.trim(),inputs:next.nodes.filter(node=>expression.includes(`@${node.name}`)).map(node=>node.id),outputType:'number',unit:'',description:'',status:'valid'};if(existing)Object.assign(existing,record);else next.formulas.push(record);return next})}
  return <div className="dialog-backdrop"><section className="analysis-center"><header><div><span>MODEL & INSIGHTS</span><h2>{mode==='formula'?'Formula Builder':mode==='simulation'?'Scenario Simulation':'Report Dashboard'}</h2></div><button aria-label="Close" onClick={close}>×</button></header><nav><button className={mode==='formula'?'active':''} onClick={()=>setMode('formula')}>Formula</button><button className={mode==='simulation'?'active':''} onClick={()=>setMode('simulation')}>Simulation</button><button className={mode==='reports'?'active':''} onClick={()=>setMode('reports')}>Reports</button></nav><main>
    {mode==='formula'&&<><label className="field-stack"><span>Target node</span><select value={targetId} onChange={event=>setTargetId(event.target.value)}>{data.nodes.map(node=><option key={node.id} value={node.id}>{node.name}</option>)}</select></label><label className="field-stack"><span>Expression</span><textarea value={expression} onChange={event=>setExpression(event.target.value)} placeholder="Example: SUM(@Revenue,@Other Income)"/></label><div className="node-chips">{data.nodes.filter(node=>node.id!==targetId).map(node=><button key={node.id} onDoubleClick={()=>setExpression(value=>`${value}@${node.name}`)} onClick={()=>setExpression(value=>`${value}@${node.name}`)}><span>{node.name}<small>{node.type}</small></span><b>＋</b></button>)}</div><button className="auth-primary" onClick={saveFormula}>Save Formula</button></>}
    {mode==='simulation'&&<><label className="field-stack"><span>Scenario</span><select value={scenarioId} onChange={event=>setScenarioId(event.target.value)}><option value="baseline">Baseline</option>{(data.scenarios||[]).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><p className="muted">Formula and scenario values are calculated from the values currently stored in this Universe.</p><div className="report-table"><table><thead><tr><th>Node</th><th>Current value</th></tr></thead><tbody>{results.map(item=><tr key={item.node.id}><td>{item.node.name}</td><td>{item.value}</td></tr>)}</tbody></table></div></>}
    {mode==='reports'&&<><div className="report-cards"><article><span>Nodes</span><b>{data.nodes.length}</b></article><article><span>Relationships</span><b>{data.relationships.length}</b></article><article><span>Formulas</span><b>{data.formulas.length}</b></article><article><span>Scenarios</span><b>{data.scenarios?.length||0}</b></article></div><div className="report-table"><table><thead><tr><th>Node</th><th>Type</th><th>Value</th></tr></thead><tbody>{data.nodes.map(node=><tr key={node.id}><td>{node.name}</td><td>{node.type}</td><td>{String(node.value||'—')}</td></tr>)}</tbody></table></div></>}
  </main></section></div>
}
